ajustes no cleaner

diff --git a/cleaner b/cleaner
--- a/cleaner
+++ b/cleaner
@@ -56,10 +56,14 @@ clean_unnecessary_packages_pacman(){
 	_packages=$(pacman -Qdtq)
 	
 	if [ -n $_packages ] ; then
-		(pacman -Rns $_packages 
-			&& log "$filename" "** $(echo $_packages | wc -l) packages removed($_packages)") 
-		||
-			(log "$filename" "** Fail to execute: pacman -Rns $_packages" && return 1)
+		pacman -Rns $_packages
+		teste=`echo $?`
+		if [ teste = "0" ] ; then
+			log "$filename" "** $(echo $_packages | wc -l) packages removed($_packages)"
+		else
+			log "$filename" "** Fail to execute: pacman -Rns $_packages"
+			return 1
+		fi
 	else
 		log "$filename" "** No unnecessary packages found"
 	fi	
